### ISSUE TITLE
Receiving 'Uncaught SyntaxError'

### ISSUE THREAD

**Issue by RyanPrentiss** [wobsoriano/nuxt-web3.js#1]
I am receiving the following error in console when using this module in lieu of the source [hack](https://github.com/nuxt/framework/discussions/4393).

`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/web3/lib/index.js?v=2fc4596f' does not provide an export named 'default' (at plugin.mjs:1:8)`

```
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
    buildModules: ['@pinia/nuxt'],
    modules: ['nuxt-web3.js'],
    typescript: {
        shim: false,
        strict: true,
        typeCheck: true,
    },
```

**Comment by baringji** [comment]
Here's a sandbox

https://codesandbox.io/s/red-platform-xdmwv1

After the page is loaded, open the sandbox link on a browser tab and see the console. There should `Uncaught SyntaxError: import not found: default` `plugin.mjs:1:7`

**Comment by wobsoriano** [comment]
Try v0.1.4

**Comment by wobsoriano** [comment]
Feel free to reopen
